package_assets: off
compress_assets: on
gzip_assets: on
javascripts:
  libraries:
    - public/javascripts/libraries/jquery-1.5.js
    - public/javascripts/libraries/jquery-ui-1.8rc3.custom.min.js
    - public/javascripts/libraries/OpenLayers.js
    - public/javascripts/libraries/jquerymx-1.0.custom.min.js
    - public/javascripts/libraries/ejs_production.js
  site:
    - public/javascripts/site/common.js
    - public/javascripts/site/helpers/navigation.js
    - public/javascripts/site/helpers/tipsy.js
    - public/javascripts/site/helpers/info.js
    - public/javascripts/site/map.js
    - public/javascripts/site/listing_controller.js
    - public/javascripts/site/watermark_controller.js
    - public/javascripts/site/directory_controller.js
    - public/javascripts/site/localization_controller.js
    - public/javascripts/site/routing_controller.js
    - public/javascripts/site/panels_controller.js
    - public/javascripts/site/init.js
stylesheets:
  site:
    - public/stylesheets/site.css